### ISSUE TITLE
feature: export command

### ISSUE THREAD

**Issue by noqqe** [noqqe/serra#10]
using json from mongodb

**Comment by pyyhttu** [comment]
My comment does not help progressing this feature, but just wanted to voice out it is awaited.

Asking also if you might have a workaround for my personal use case:

I have a html-based card list on a web server which is handy to view through browser when mobile. However, I haven't been able to update that list in a while after moved to serra. Basically the wanted format is just:

```
1 Abduction
1 Abeyance
1 Absorb
1 Abuna Acolyte
1 Abundance
1 Abyssal Persecutor
[...]
```

I was thinking: Does the docker stack in this repo offer tools to pipe the card list in above format to a file from mongosh already now?

I've researched this for a while with pointers from https://stackoverflow.com/questions/22565231/printing-mongo-query-output-to-a-file-while-in-the-mongo-shell but haven't yet landed on a solution.

**Comment by noqqe** [comment]
Did you now that there is a web version included in `serra` ? 

try `./serra web` and visit localhost:8080

**Comment by pyyhttu** [comment]
> @pyyhttu Did you now that there is a web version included in serra ?

I did not. But now that I did `git pull origin main` on my test machine (laptop) I notice there is `/templates/index.tmpl`. So doing `./serra web` spawns a really nice web front end and I can use that as a workaround!

But it is different from export.

I'll continue to research what kind of query I need to construct in Serra's Mongodb. I need the cards in a list that has: amount, card name and then the list is ordered by the date & time the card was added, newest on the bottom.

**Comment by noqqe** [comment]
export command is there now since version 3.13.0 supports json and csv so far. may be enhanced with other formats in the future, but not in the scope of this issue

**Comment by pyyhttu** [comment]
> version 3.13.0 supports json and csv so far

Hmm... Exporting to json works great with: 

`./serra export -f json -e usg > usg.json`

But could you elaborate how do I export to csv?

I [searched](https://github.com/search?q=repo%3Anoqqe%2Fserra+%28json+OR+csv%29&type=code) the code repository for the pointers, as well as `./serra export --help` but both mention only .json:

```
Export cards from your collection.
                Your data. Your choice.
                Supports multiple output formats depending on where you want to export your collection.

Usage:
  serra export [flags]

Flags:
  -f, --format string   Choose format to export (tcgpowertools/json) (default "tcgpowertools")
  -h, --help            help for export
  -e, --set string      Filter by set code (usg/mmq/vow)
```
